name: 'Compile Go' # taken from https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
description: 'Compiles a golang project'
inputs:
  go-version:
    description: 'Version of golang to use'
    required: false
    default: '~1.17'
  working-directory:
    description: 'Directory to run the command from'
    required: false
    default: '.'
  command:
    description: 'Command to run'
    required: false
    default: "go build -race ./..."
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go With Caching
      uses: magnetikonline/action-golang-cache@v1
      with:
        go-version: inputs.go-version
    - name: Compile
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        ${{ inputs.compile-command }}